### ISSUE TITLE
Train ChemProt model problem

### ISSUE THREAD

**Issue by rockman1989** [dwadden/dygiepp#17]
I met a problem when I trained ChemProt model
when I run "bash ./scripts/train/train_chemprot.sh -1"
-----------------------------------------------------------------------------------------------------
2020-05-27 14:17:59,641 - INFO - allennlp.training.optimizers - Number of trainable parameters: 123007840
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.optimizer.infer_type_and_cast = True
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.optimizer.lr = 0.001
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.optimizer.t_total = 10000
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.optimizer.warmup = 0.1
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.optimizer.weight_decay = 0
2020-05-27 14:17:59,642 - INFO - allennlp.common.registrable - instantiating registered subclass bert_adam of <class 'allennlp.training.optimizers.Optimizer'>
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.type = reduce_on_plateau
2020-05-27 14:17:59,642 - INFO - allennlp.common.registrable - instantiating registered subclass reduce_on_plateau of <class 'allennlp.training.learning_rate_schedulers.learning_rate_scheduler.LearningRateScheduler'>
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.factor = 0.5
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.mode = max
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.patience = 4
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.num_serialized_models_to_keep = 3
2020-05-27 14:17:59,642 - INFO - allennlp.common.params - trainer.keep_serialized_model_every_num_seconds = None
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.model_save_interval = None
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.summary_interval = 100
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.histogram_interval = None
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.should_log_parameter_statistics = True
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.should_log_learning_rate = False
2020-05-27 14:17:59,643 - INFO - allennlp.common.params - trainer.log_batch_size_period = None
2020-05-27 14:17:59,806 - INFO - allennlp.training.trainer - Beginning training.
2020-05-27 14:17:59,806 - INFO - allennlp.training.trainer - Epoch 0/249
2020-05-27 14:17:59,806 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 2505.212
2020-05-27 14:17:59,891 - INFO - allennlp.training.trainer - Training
  0%|          | 0/1299 [00:00<?, ?it/s]./scripts/train/train_chemprot.sh: line 18:  6835 Killed                  ie_train_data_path=$data_root/training.jsonl ie_dev_data_path=$data_root/development.jsonl ie_test_data_path=$data_root/test.jsonl cuda_device=$cuda_device allennlp train $config_file --cache-directory $data_root/cached --serialization-dir ./models/$experiment_name --include-package dygie

---------------------------------------------------------------------------------------------------------
I think the reason for this problem is that the memmory is too small. I would like to hear your advice.
my cloud server:
2vCPUs  |   4GB

**Comment by dwadden** [comment]
Hmm so the only error message you get is `6835 Killed`, is that right? Can you successfully train any other model (for instance, SciERC)?

If not, maybe set a smaller batch size in the [config file](https://github.com/dwadden/dygiepp/blob/master/training_config/chemprot.jsonnet#L72)? Let me know if that doesn't work.

**Comment by rockman1989** [comment]
6835 Killed is the only error, then I ran"bash ./scripts/train/train_genia_lightweight.sh -1", got the same problem. set smaller batch size in the config file "batch_size: 0"
 run "bash ./scripts/train/train_chemprot.sh -1" 
---------------------------------------------------------------------------------------------------
2020-05-27 16:39:27,031 - INFO - allennlp.training.optimizers - Number of trainable parameters: 123007840
2020-05-27 16:39:27,031 - INFO - allennlp.common.params - trainer.optimizer.infer_type_and_cast = True
2020-05-27 16:39:27,031 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.lr = 0.001
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.t_total = 10000
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.warmup = 0.1
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.weight_decay = 0
2020-05-27 16:39:27,032 - INFO - allennlp.common.registrable - instantiating registered subclass bert_adam of <class 'allennlp.training.optimizers.Optimizer'>
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.type = reduce_on_plateau
2020-05-27 16:39:27,032 - INFO - allennlp.common.registrable - instantiating registered subclass reduce_on_plateau of <class 'allennlp.training.learning_rate_schedulers.learning_rate_scheduler.LearningRateScheduler'>
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.factor = 0.5
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.mode = max
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.patience = 4
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.num_serialized_models_to_keep = 3
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.keep_serialized_model_every_num_seconds = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.model_save_interval = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.summary_interval = 100
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.histogram_interval = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.should_log_parameter_statistics = True
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.should_log_learning_rate = False
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.log_batch_size_period = None
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Beginning training.
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Epoch 0/249
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 2986.84
2020-05-27 16:39:27,052 - ERROR - allennlp.common.util - unable to check gpu_memory_mb(), continuing
Traceback (most recent call last):
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/common/util.py", line 378, in gpu_memory_mb
    encoding='utf-8')
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
2020-05-27 16:39:27,056 - INFO - allennlp.training.trainer - Training
  0%|          | 0/5194 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 352, in _train_epoch
    self.optimizer.step()
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/pytorch_pretrained_bert/optimization.py", line 262, in step
    state['next_m'] = torch.zeros_like(p.data)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 95588352 bytes. Error code 12 (Cannot allocate memory)

**Comment by rockman1989** [comment]
> Hmm so the only error message you get is `6835 Killed`, is that right? Can you successfully train any other model (for instance, SciERC)?
> 
> If not, maybe set a smaller batch size in the [config file](https://github.com/dwadden/dygiepp/blob/master/training_config/chemprot.jsonnet#L72)? Let me know if that doesn't work.

6835 Killed is the only error, then I ran"bash ./scripts/train/train_genia_lightweight.sh -1", got the same problem. set smaller batch size in the config file "batch_size: 2"
run "bash ./scripts/train/train_chemprot.sh -1"
2020-05-27 16:39:27,031 - INFO - allennlp.training.optimizers - Number of trainable parameters: 123007840
2020-05-27 16:39:27,031 - INFO - allennlp.common.params - trainer.optimizer.infer_type_and_cast = True
2020-05-27 16:39:27,031 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.lr = 0.001
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.t_total = 10000
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.warmup = 0.1
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.optimizer.weight_decay = 0
2020-05-27 16:39:27,032 - INFO - allennlp.common.registrable - instantiating registered subclass bert_adam of <class 'allennlp.training.optimizers.Optimizer'>
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.type = reduce_on_plateau
2020-05-27 16:39:27,032 - INFO - allennlp.common.registrable - instantiating registered subclass reduce_on_plateau of <class 'allennlp.training.learning_rate_schedulers.learning_rate_scheduler.LearningRateScheduler'>
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.factor = 0.5
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.mode = max
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.learning_rate_scheduler.patience = 4
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.num_serialized_models_to_keep = 3
2020-05-27 16:39:27,032 - INFO - allennlp.common.params - trainer.keep_serialized_model_every_num_seconds = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.model_save_interval = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.summary_interval = 100
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.histogram_interval = None
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.should_log_parameter_statistics = True
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.should_log_learning_rate = False
2020-05-27 16:39:27,033 - INFO - allennlp.common.params - trainer.log_batch_size_period = None
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Beginning training.
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Epoch 0/249
2020-05-27 16:39:27,052 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 2986.84
2020-05-27 16:39:27,052 - ERROR - allennlp.common.util - unable to check gpu_memory_mb(), continuing
Traceback (most recent call last):
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/common/util.py", line 378, in gpu_memory_mb
encoding='utf-8')
File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 411, in check_output
**kwargs).stdout
File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 488, in run
with Popen(*popenargs, **kwargs) as process:
File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 800, in init
restore_signals, start_new_session)
File "/root/miniconda3/envs/dygiepp/lib/python3.7/subprocess.py", line 1482, in _execute_child
restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
2020-05-27 16:39:27,056 - INFO - allennlp.training.trainer - Training
0%| | 0/5194 [00:02<?, ?it/s]
Traceback (most recent call last):
File "/root/miniconda3/envs/dygiepp/bin/allennlp", line 8, in
sys.exit(run())
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
main(prog="allennlp")
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/init.py", line 102, in main
args.func(args)
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
args.cache_prefix)
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
cache_directory, cache_prefix)
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
metrics = trainer.train()
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
train_metrics = self._train_epoch(epoch)
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 352, in _train_epoch
self.optimizer.step()
File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/pytorch_pretrained_bert/optimization.py", line 262, in step
state['next_m'] = torch.zeros_like(p.data)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 95588352 bytes. Error code 12 (Cannot allocate memory)

**Comment by dwadden** [comment]
Hmm I've never seen this before. Honestly my only advice is to get a bigger machine? You can always get free GPU's from [colab.research.google.com](Google colab).
