### ISSUE TITLE
Trying to apply the pre-trained ACE05-Event model to new data

### ISSUE THREAD

**Issue by dhruv4** [dwadden/dygiepp#18]
Hi there! We're trying use the pre-trained ACE05-Event model for a project on new data. However, we've been struggling to get it to run. In order to test it out, we tried the following on a line of data from the SciERC dataset and got the error below.

```
!echo '{"events": [[], [], [], [], []], "clusters": [[[6, 17], [32, 32]], [[4, 4], [55, 55], [91, 91]], [[58, 62], [64, 64], [79, 79]]], "sentences": [["This", "paper", "presents", "an", "algorithm", "for", "computing", "optical", "flow", ",", "shape", ",", "motion", ",", "lighting", ",", "and", "albedo", "from", "an", "image", "sequence", "of", "a", "rigidly-moving", "Lambertian", "object", "under", "distant", "illumination", "."], ["The", "problem", "is", "formulated", "in", "a", "manner", "that", "subsumes", "structure", "from", "motion", ",", "multi-view", "stereo", ",", "and", "photo-metric", "stereo", "as", "special", "cases", "."], ["The", "algorithm", "utilizes", "both", "spatial", "and", "temporal", "intensity", "variation", "as", "cues", ":", "the", "former", "constrains", "flow", "and", "the", "latter", "constrains", "surface", "orientation", ";", "combining", "both", "cues", "enables", "dense", "reconstruction", "of", "both", "textured", "and", "texture-less", "surfaces", "."], ["The", "algorithm", "works", "by", "iteratively", "estimating", "affine", "camera", "parameters", ",", "illumination", ",", "shape", ",", "and", "albedo", "in", "an", "alternating", "fashion", "."], ["Results", "are", "demonstrated", "on", "videos", "of", "hand-held", "objects", "moving", "in", "front", "of", "a", "fixed", "light", "and", "camera", "."]], "ner": [[[4, 4, "Generic"], [6, 17, "Task"], [20, 21, "Material"], [24, 26, "Material"], [28, 29, "OtherScientificTerm"]], [[32, 32, "Generic"], [42, 42, "Material"], [44, 45, "Material"], [48, 49, "Material"]], [[55, 55, "Generic"], [58, 62, "OtherScientificTerm"], [64, 64, "Generic"], [67, 67, "Generic"], [69, 69, "OtherScientificTerm"], [72, 72, "Generic"], [74, 75, "OtherScientificTerm"], [79, 79, "Generic"], [81, 88, "Task"]], [[91, 91, "Generic"], [95, 105, "Method"]], [[115, 118, "Material"]]], "relations": [[[4, 4, 6, 17, "USED-FOR"], [20, 21, 4, 4, "USED-FOR"], [24, 26, 20, 21, "FEATURE-OF"], [28, 29, 24, 26, "FEATURE-OF"]], [[42, 42, 44, 45, "CONJUNCTION"], [44, 45, 48, 49, "CONJUNCTION"]], [[58, 62, 55, 55, "USED-FOR"], [67, 67, 64, 64, "HYPONYM-OF"], [67, 67, 69, 69, "USED-FOR"], [67, 67, 72, 72, "CONJUNCTION"], [72, 72, 64, 64, "HYPONYM-OF"], [72, 72, 74, 75, "USED-FOR"], [79, 79, 81, 88, "USED-FOR"]], [[95, 105, 91, 91, "USED-FOR"]], []], "doc_key": "ICCV_2003_158_abs"}' > scierc-test.jsonl
!allennlp predict pretrained/ace05-event.tar.gz \
    scierc-test.jsonl \
    --predictor dygie \
    --include-package dygie \
    --use-dataset-reader \
    --output-file predictions/scierc-test.jsonl
```
This is the error:
```
2020-06-09 22:19:37,555 - ERROR - allennlp.data.vocabulary - Namespace: ner_labels
2020-06-09 22:19:37,555 - ERROR - allennlp.data.vocabulary - Token: Generic
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/predict.py", line 227, in _predict
    manager.run()
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/predict.py", line 201, in run
    for model_input_instance, result in zip(batch, self._predict_instances(batch)):
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/predict.py", line 159, in _predict_instances
    results = [self._predictor.predict_instance(batch_data[0])]
  File "./dygie/predictors/dygie.py", line 81, in predict_instance
    dataset.index_instances(model.vocab)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset.py", line 155, in index_instances
    instance.index_fields(vocab)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/instance.py", line 72, in index_fields
    field.index(vocab)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/fields/sequence_label_field.py", line 100, in index
    for label in self.labels]
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/fields/sequence_label_field.py", line 100, in <listcomp>
    for label in self.labels]
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/vocabulary.py", line 637, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
```
We aren't super familiar with allennlp, so we aren't sure how to diagnose this issue. We're not sure why there is an issue with the NER_labels as we're hoping to just predict those, rather than train the model on them. Is there a way to override this?

Thanks a lot!

**Comment by dhruv4** [comment]
We are dumb. We solved this by just having the sentences and doc label in the json.

Thanks!

**Comment by cpaaax** [comment]
> We are dumb. We solved this by just having the sentences and doc label in the json.
> 
> Thanks!

Hi, we also want to use the pre-trained ACE05-Event model for our own dataset, and run into the issue you mentioned. What do you mean by "having the sentences and doc label in the json"? Is it convenient for you to give an example of json? 

Thanks!

**Comment by dwadden** [comment]
The instructions here might help: https://github.com/dwadden/dygiepp/blob/master/doc/data.md#formatting-a-new-dataset. Your input should come as a `.jsonl` file. Each line should have a `sentences` field and a `doc_key` field. If this doesn't work for you, feel free to share the dataset you're trying to make predictions on.

**Comment by dhruv4** [comment]
Here's an example of one of the lines we used in the .jsonl file!
`{'doc_key': '0', 'sentences': [['Coronavirus', 'Thwarts', 'Rescue', 'of', 'Endangered', 'Albatrosses', 'Menaced', 'by', 'Giant', 'Mice'], ['The', 'covid-19', 'pandemic', 'has', 'forced', 'a', 'delay', 'to', 'an', 'effort', 'to', 'protect', 'vulnerable', 'seabirds', 'from', 'large,', 'invasive', 'mice', 'on', 'an', 'island', 'in', 'the', 'South', 'Atlantic', 'Ocean.']]}`

**Comment by cpaaax** [comment]
@dhruv4 Great, thank you!
