### ISSUE TITLE
How to run my dataset

### ISSUE THREAD

**Issue by rockman1989** [dwadden/dygiepp#20]
I have some problem here.
--------------------------------------------------------------
2020-06-11 21:22:09,219 - INFO - allennlp.training.trainer - Beginning training.
2020-06-11 21:22:09,219 - INFO - allennlp.training.trainer - Epoch 0/249
2020-06-11 21:22:09,219 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 3337.832
2020-06-11 21:22:09,275 - INFO - allennlp.training.trainer - Training
  0%|          | 0/1990 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./dygie/models/dygie.py", line 280, in forward
    output_relation = self._relation.predict_labels(relation_labels, output_relation, metadata)
  File "./dygie/models/relation.py", line 193, in predict_labels
    predictions = self.decode(output_dict)["decoded_relations_dict"]
  File "./dygie/models/relation.py", line 218, in decode
    top_spans, predicted_relations, num_spans_to_keep)
  File "./dygie/models/relation.py", line 249, in _decode_sentence
    label_name = self.vocab.get_token_from_index(label, namespace="relation_labels")
  File "/root/miniconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 644, in get_token_from_index
    return self._index_to_token[namespace][index]
KeyError: 0

**Comment by dwadden** [comment]
I can help debug if you can provide a minimal reproducible example, including data and the script you're using to kick off model training.

**Comment by dwadden** [comment]
Did you end up fixing this? I added some documentation on [working with new datasets](https://github.com/dwadden/dygiepp#working-with-new-datasets).

I'll close this for now. If you're still having issues, feel free to reopen.
