### ISSUE TITLE
Event extraction training without Named Entities or Relations

### ISSUE THREAD

**Issue by GillesJ** [dwadden/dygiepp#34]
My custom dataset has ACE-like event annotations with triggers and arguments but no NER or relations.
I tried running the ACE training pipeline on my event data and left the `relations` and `ner` keys empty, e.g.:
```json
{
"doc_key": "aal00",
"sentences": [
    ["American", "Airlines", "Up", "on", "Record", "April", "Traffic", ",", "Upbeat", "Q2", "View"],
    ["Premier", "passenger", "carrier", ",", "American", "Airlines", "Group", "Inc", ".", "AAL", "saw", "its", "shares", "rise", "4.76", "%", "to", "$", "47.08", "at", "the", "close", "of", "business", "on", "Apr", "9", ",", "following", "the", "release", "of", "its", "traffic", "report", "for", "the", "month", "of", "April", "."]
],
"events": [
    [ ],
    [
        [[24, "SecurityValue"], [25, 26, "IncreaseAmount"], [23, 23, "Security"], [30, 37, "TIME"], [28, 29, "Price"]],
        [[45, "FinancialReport"], [43, 43, "Reportee"], [46, 50, "TIME"]]
    ]
],
"ner": [
    [ ],
    [ ]
],
"relations": [
    [ ],
    [ ]
],
"clusters": [
    [ ],
    [ ]
]
}
```

I configured the .jsonnet file based off `train_ace05_event.jsonnet` changing
`n_trigger_labels` to the amount of event types and `n_ner_labels: 0,` because I have no NER annotations.
Those were all the relevant config keys I could identify from the file itself, I probably missed some because training failed with the following error:
```
2020-08-06 14:18:05,035 - INFO - allennlp.training.trainer - Training
  0%|          | 0/365 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./dygie/models/dygie.py", line 298, in forward
    ner_labels, metadata)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./dygie/models/events.py", line 267, in forward
    trig_arg_embeddings, top_trig_scores, top_arg_scores, top_arg_mask)
  File "./dygie/models/events.py", line 553, in _compute_argument_scores
    embeddings_flat = pairwise_embeddings.view(-1, feature_dim)
RuntimeError: shape '[-1, 2642]' is invalid for input of size 17840250
```
- Is it possible to train Event extraction with only events (trigger + arguments) without NER and relation annotations?
- Am I missing a config key to set here? I suspect the amount of argument types has to be set somewhere but the config for this is not obvious.

**Comment by dwadden** [comment]
This should be doable. In your `jsonnet` config file, set the `loss_weights` on all modules other event extraction to 0. See here: https://github.com/dwadden/dygiepp/blob/master/training_config/ace05_event.jsonnet#L42.

**Comment by GillesJ** [comment]
I tried setting the `loss_weights: ner:` to 0 in config and also setting `n_ner_labels` to 0, but training errors with
```
2020-08-14 08:45:43,915 - INFO - allennlp.training.trainer - Training
  0%|          | 0/183 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 256, in batch_loss
    output_dict = training_util.data_parallel(batch_group, self.model, self._cuda_devices)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/util.py", line 331, in data_parallel
    outputs = parallel_apply(replicas, inputs, moved, used_device_ids)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in replica 0 on device 2.
Original Traceback (most recent call last):
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./dygie/models/dygie.py", line 298, in forward
    ner_labels, metadata)
  File "/opt/conda/envs/dygiepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./dygie/models/events.py", line 183, in forward
    ner_scores = output_ner["ner_scores"]
KeyError: 'ner_scores'
```
Seems to that in `events.py` the ner_scores are not optional right now as they are passed as a req. arg. to the `_mention_pruner` func.

For now I am testing the pipeline by producing NER predictions from the pre-trained ACE05-event model on my custom data and feeding that into the model for silver-standard reference NER labels.

I set `event_args_use_ner_labels` to `false` too. Is this required or are the NER labels referred to here model predictions not based off gold-standard labels?
I get higher F1 for TrigC and ArgC when setting this to false when training with NER labels produced by prediction from the pre-trained ACE05 model.)

**Comment by GillesJ** [comment]
I cannot re-open this issue since I am not a maintainer so I made a new one here: https://github.com/dwadden/dygiepp/issues/35 #35
