### ISSUE TITLE
Problem running script to train model on custom dataset

### ISSUE THREAD

**Issue by ValaryLim** [dwadden/dygiepp#72]
Hi, 

I'm currently trying to train a model on a new dataset. I've successfully run normalized.py and collate.py on my processed_data dataset, and am now trying to run the train.sh script on the custom data. My new dataset is very similar to scierc, except that it adds 3 additional relations (neucause, negcause and poscause). 

I'm currently getting this error message when I run bash scripts/train.sh custom: 
```
Traceback (most recent call last):
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 118, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 177, in train_model_from_file
    file_friendly_logging=file_friendly_logging,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 238, in train_model
    file_friendly_logging=file_friendly_logging,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 433, in _train_worker
    local_rank=process_rank,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 595, in from_params
    **extras,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 624, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/train.py", line 625, in from_partial_objects
    test_data_path=test_data_path,
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/training/util.py", line 105, in read_all_datasets
    train_data = dataset_reader.read(train_data_path)
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 229, in read
    instances = list(instances)
  File "/Users/valarylim/opt/anaconda3/envs/dygiepp/lib/python3.7/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 53, in _read
    instance = self.text_to_instance(doc_text)
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 197, in text_to_instance
    fields = self._process_sentence_fields(doc)
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 165, in _process_sentence_fields
    sentence_fields = [self._process_sentence(sent, doc.dataset) for sent in doc.sentences]
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 165, in <listcomp>
    sentence_fields = [self._process_sentence(sent, doc.dataset) for sent in doc.sentences]
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 149, in _process_sentence
    relation_labels, relation_indices = self._process_relations(span_tuples, sent)
  File "/Users/valarylim/dygiepp/dygie/data/dataset_readers/dygie.py", line 91, in _process_relations
    ix2 = span_tuples.index(span2)
ValueError: (-71, -67) is not in list
```
Could I get some assistance resolving this error? Thank you for your help!

**Comment by dwadden** [comment]
Hmm, seems like you've got text spans that are being associated with negative indices, which shouldn't happen. Can you create a minimal example and attach it here? This should include:

- The training instance causing the error. This should be a single sentence, or at most a single document.
- A script to kick off model training that produces the error.

I'll try to run it and see what's going on.

**Comment by ValaryLim** [comment]
Thanks for your help!

I've attached a sample of the train.json, dev.json, and test.json files used. They're currently identical to each other. I've placed them under the data/custom/processed_data/json directory. 
[json.zip](https://github.com/dwadden/dygiepp/files/7074077/json.zip)

I first run the normalized_data function and collated_data function:
```
python scripts/data/shared/normalize.py \
    data/custom/processed_data/json \
    data/custom/normalized_data/json \
    --file_extension=json \
    --max_tokens_per_doc=0 \
    --dataset=custom

python scripts/data/shared/collate.py \
    data/custom/processed_data/json \
    data/custom/collated_data/json \
    --file_extension=json \
    --dataset=custom
```

And the code generates the above error when I run `bash scripts/train.sh custom`

**Comment by dwadden** [comment]
The first argument to `train.sh` is the name of the training config. So, for your command, the training script will look for a file under `training_config/custom.jsonnet`. As far as I can see, you didn't include this in your zip file. Can you include the training config you're using?

**Comment by ValaryLim** [comment]
Sorry about that! I've re-attached a zip file with the training config I'm using. 

[dygiepp_test.zip](https://github.com/dwadden/dygiepp/files/7112913/dygiepp_test.zip)

**Comment by dwadden** [comment]
OK, I think I found it. The issue is in line 2 (which corresponds to `doc_key: 1`) of `data/custom/collated_data/json/train.json`. If you look at the `relations` field for that entry, the first three lists are empty, and the fourth one has an entry `[98, 101, 5, 9, "PART-OF"]`. When the model tries to convert those document-level indices to sentence-level indices, it gets negative numbers, which is causing the error you're getting. Those indices must be wrong.

Two possibilities: either there's an issue with the annotations coming in, or there's a bug in my `normalize` or `collate` scripts. Can you determine which it is? Ideally, write a script like `check_annotation_indices` that checks that all your entity and relation indices are in-bounds and submit a PR (I'm sure this would be useful for others). If the data look OK before running my processing scripts but are weird after, let me know and I can debug my data processing scripts.
