### ISSUE TITLE
Error in event predict model

### ISSUE THREAD

**Issue by unlimit11** [dwadden/dygiepp#80]
Hi, i want use ACE event evaluate model by pip.  but apparently there is a problem in the code. please help, thank you.

(dygiepp) ➜  dygiepp allennlp evaluate \                                                                                   
ace05-event.tar.gz \
dygie/tests/fixtures/collate/ace-event/test.json \
--cuda-device -1 \
--include-package dygie
2021-11-20 17:58:27,812 - INFO - allennlp.common.plugins - Plugin allennlp_models available
Traceback (most recent call last):
  File "/home/mohammad/PycharmProjects/venv/dygiepp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/mohammad/PycharmProjects/venv/dygiepp/lib/python3.9/site-packages/allennlp/__main__.py", line 46, in run
    main(prog="allennlp")
  File "/home/mohammad/PycharmProjects/venv/dygiepp/lib/python3.9/site-packages/allennlp/commands/__init__.py", line 122, in main
    import_module_and_submodules(package_name)
  File "/home/mohammad/PycharmProjects/venv/dygiepp/lib/python3.9/site-packages/allennlp/common/util.py", line 362, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/home/mohammad/PycharmProjects/venv/dygiepp/lib/python3.9/site-packages/allennlp/common/util.py", line 351, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/mohammad/PycharmProjects/dygiepp/dygie/data/__init__.py", line 1, in <module>
    from dygie.data.dataset_readers.dygie import DyGIEReader
  File "/home/mohammad/PycharmProjects/dygiepp/dygie/data/dataset_readers/dygie.py", line 29, in <module>
    class DyGIEReader(DatasetReader):
  File "/home/mohammad/PycharmProjects/dygiepp/dygie/data/dataset_readers/dygie.py", line 203, in DyGIEReader
    def _instances_from_cache_file(self, cache_filename):
  File "/home/mohammad/PycharmProjects/venv/dygiepp/lib/python3.9/site-packages/overrides/overrides.py", line 67, in overrides
    raise AssertionError('No super class method found for "%s"' % method.__name__)
**AssertionError: No super class method found for "_instances_from_cache_file"**

**Comment by dwadden** [comment]
Hi,

Can you confirm that you've created a conda environment as in the dependencies section of the [README](https://github.com/dwadden/dygiepp#dependencies)? It looks like you're using Python 3.9, and I've only tested DyGIE on Python 3.7.

**Comment by unlimit11** [comment]
solved with python3.7.4. thank you.

**Comment by unlimit11** [comment]
I use this [model](https://ai2-s2-research.s3-us-west-2.amazonaws.com/dygiepp/master/ace05-event.tar.gz)  and [datasheet](https://github.com/dwadden/dygiepp/blob/master/dygie/tests/fixtures/collate/ace-event/test.json)  below to evaluate the model.

allennlp evaluate \
  ace05-event.tar.gz \
  dygie/tests/fixtures/collate/ace-event/test.json \
  --cuda-device -1 \
  --include-package dygie

The required models were loaded correctly. but i have error, apparently the problem is in dataset.

  File "/venv/dygiepp/lib/python3.7/site-packages/allennlp/data/fields/list_field.py", line 55, in index
    field.index(vocab)
  File "/venv/dygiepp/lib/python3.7/site-packages/allennlp/data/fields/label_field.py", line 91, in index
    self.label, self._label_namespace  # type: ignore
  File "//venv/dygiepp/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 695, in get_token_index
    f"'{token}' not found in vocab namespace '{namespace}', and namespace "
**KeyError: "'' not found in vocab namespace 'None__ner_labels', and namespace does not contain the default OOV token ('@@UNKNOWN@@')"**

Please advise what the input data format to evaluate the model and how can this error be fixed? thanks

**Comment by dwadden** [comment]
See the [README](https://github.com/dwadden/dygiepp#working-with-new-datasets) for info on label namespaces. The test fixture doesn't have a `dataset` field. If you add one, things should work.

**Comment by unlimit11** [comment]
ُُThank you very much.

A workable example for others:
`{"dataset": "ace-event","doc_key": "0", "sentences": [["Coronavirus", "Thwarts", "Rescue", "of", "Endangered", "Albatrosses", "Menaced", "by", "Giant", "Mice"], ["The", "covid-19", "pandemic", "has", "forced", "a", "delay", "to", "an", "effort", "to", "protect", "vulnerable", "seabirds", "from", "large", "invasive", "mice", "on", "an", "island", "in", "the", "South", "Atlantic", "Ocean."]]}
`

**Comment by dwadden** [comment]
Thanks for posting this!
